# Generated by Django 3.1.3 on 2023-02-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='questions',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson_key',
            new_name='lesson',
        ),
        migrations.AddField(
            model_name='choice',
            name='lesson',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
            preserve_default=False,
        ),
    ]
