# Generated by Django 3.1.3 on 2023-02-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230206_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='questions',
        ),
    ]
